# This is a basic workflow that is manually triggered

name: Package DuckDB Taco

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Taco
      uses: actions/checkout@v3
      with:
        path: taco

    - name: Checkout SDK
      uses: actions/checkout@v3
      with:
        repository: tableau/connector-plugin-sdk
        path: sdk
    
    - name: Create Virtual Environment
      shell: bash
      run: |
        pushd sdk
        python -m venv .venv
        popd
      
    - name: Package Taco
      shell: bash
      run: |
        pushd sdk
        source .venv/bin/activate
        cd connector-packager
        python setup.py install
        python -m connector_packager.package ../../taco/tableau_connectors/duckdb_jdbc
        popd

    - uses: actions/upload-artifact@v3
      with:
        name: duckdb_taco
        path: |
          sdk/connector-packager/packaged-connector/duckdb_jdbc.taco
